import './normalize.scss'
import React from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout